[package]
name = "dsp_world_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
bitflags = "2.4.1"
lerp = "0.5"

[dependencies.dotnet35_rand_rs]
version = "0.2.0"
